project:
  type: website
  output-dir: docs
exectute:
  echo: true
website:
  title: "Data-Based Economics"
  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Slides"
          contents:
            - session_1/index.qmd
            - session_2/index.qmd
            - session_3/index.qmd
            - session_4/index.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: true