project:
  type: website
  output-dir: docs
exectute:
  echo: true
website:
  title: "Data-Based Economics"
  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Handouts"
          contents:
            - session_1/index.qmd
            - session_2/index.qmd
            - session_3/index.qmd
            - session_4/index.qmd
            - session_6/index.qmd
            - session_7/index.qmd
            - session_8/index.qmd
            - session_9/index.qmd
            - ai/index.qmd

        - section: "Tutorials"
          contents:
            - session_3/Philips_curve_correction.ipynb
            - session_4/Regressions_correction_2022.ipynb
            - session_6/instrumental_variables_correction.ipynb
            - session_7/machine_learning_regressions_correction.ipynb
            - session_8/Classification_Correction.ipynb
format:
  html:
    theme: flatly
    css: styles.css
    toc: true